### ISSUE TITLE
Need uniform depthTexture

### ISSUE THREAD

**Issue by RomainFranck** [newincpp/G_Rand#1]
Hiya, I need the depth of the frags to do the ssao shader

**Comment by newincpp** [comment]
i will check how to do it by tomorrow and if it is fast to implement you will see it very very soon. if it's not, because i lack of time i don't know when i will take time to implement it.

**Comment by newincpp** [comment]
It need some yak shaving so you will have to wait... Except if you want to implement RTT and textures...

**Comment by RomainFranck** [comment]
urgh, I'll do it then

**Comment by newincpp** [comment]
added as "uniform sampler2D gDepth"
